services:
  - type: web
    plan: free
    name: PYRO-RENAME-BOT
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/TEAM-PYRO-BOTZ/PYRO-RENAME-BOT.git      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH
        sync: false
      
    autoDeploy: false 
Footer
© 2023 GitHub, Inc.
Footer navigation
Terms
Privacy
